const assert = require("node:assert/strict");
const { registered, unregistered } = require("./readers.js");
assert.equal(registered(), "fake-module-secret");
const secrets = unregistered();
assert.deepEqual(Object.keys(secrets), []);
assert.equal(secrets.DATABASE_URL, undefined);
assert.equal(Object.getPrototypeOf(secrets), null);
assert.equal(Object.isFrozen(secrets), true);
assert.throws(() => process.env.DATABASE_URL, { code: "FORTENV_ACCESS_DENIED" });
console.log("ok");
